services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3300:3300
    volumes:
      - "./srv/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
    networks:
      - joomla_network

  joomla:
    image: joomla:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:80
    restart: always
    environment:
      JOOMLA_DB_HOST: mysql
      JOOMLA_DB_USER: joomla
      JOOMLA_DB_PASSWORD: joomla
      JOOMLA_DB_NAME: joomla
    volumes:
      - ./srv/joomla/:/var/www/html
      - ./template/:/var/www/html/joomla/templates/new
      - ./plugin/:/var/www/html/joomla/plugins/new
      - ./srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - joomla_network

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: joomla
      MYSQL_ROOT_PASSWORD: joomla
      PMA_HOST: mysql
    networks:
      - joomla_network

networks:
  joomla_network:
